#!/bin/bash
# Skript pro vytvoření PostgreSQL databáze na Render.com
# Tento skript vám pomůže s procesem vytváření databáze

echo "🚀 Vytvoření PostgreSQL databáze na Render.com"
echo ""
echo "Tento skript vás provede procesem vytváření databáze."
echo "Databázi musíte vytvořit přes webové rozhraní Render.com."
echo ""
echo "=== KROK 1: Otevřete Render Dashboard ==="
echo "👉 Jděte na: https://dashboard.render.com"
echo ""
read -p "Stiskněte Enter, až budete na Render Dashboard..."

echo ""
echo "=== KROK 2: Vytvořte PostgreSQL databázi ==="
echo "1. Klikněte na tlačítko 'New +' (vpravo nahoře)"
echo "2. Vyberte 'PostgreSQL'"
echo ""
read -p "Stiskněte Enter, až budete na stránce vytváření databáze..."

echo ""
echo "=== KROK 3: Vyplňte údaje ==="
echo "Vyplňte následující údaje:"
echo ""
echo "📝 Name: crypto-price-alert-db (nebo jakýkoliv název)"
echo "📝 Database: cryptodb"
echo "📝 User: cryptouser"
echo "📝 Region: STEJNÁ jako váš Web Service (důležité!)"
echo "📝 Plan: Free (pro začátek)"
echo ""
read -p "Stiskněte Enter, až vyplníte údaje a kliknete na 'Create Database'..."

echo ""
echo "⏳ Počkejte 1-2 minuty, až se databáze vytvoří..."
read -p "Stiskněte Enter, až bude databáze vytvořena..."

echo ""
echo "=== KROK 4: Zkopírujte Internal Database URL ==="
echo "1. Jděte na vaši databázi (v seznamu služeb)"
echo "2. V sekci 'Connections' najděte 'Internal Database URL'"
echo "3. Klikněte na 'Copy' a zkopírujte URL"
echo ""
echo "URL vypadá nějak takto:"
echo "postgresql://cryptouser:password@dpg-xxxxx-a/cryptodb"
echo ""
read -p "Zkopírovali jste Internal Database URL? (Enter pro pokračování)..."

echo ""
echo "=== KROK 5: Přidejte DATABASE_URL do vašeho service ==="
echo "1. Jděte na váš Web Service (crypto price alert bot)"
echo "2. Klikněte na záložku 'Environment'"
echo "3. Klikněte na 'Add Environment Variable'"
echo "4. Přidejte:"
echo "   Key: DATABASE_URL"
echo "   Value: [vložte zkopírovanou Internal Database URL]"
echo "5. Klikněte na 'Save Changes'"
echo ""
read -p "Přidali jste DATABASE_URL? (Enter pro pokračování)..."

echo ""
echo "✅ Hotovo! Render automaticky restartuje service."
echo ""
echo "=== OVĚŘENÍ ==="
echo "1. Jděte na 'Logs' vašeho service"
echo "2. Měli byste vidět:"
echo "   ✅ Databáze připravena - data budou persistentní a přežijí redeploy"
echo ""
echo "Pokud vidíte varování, zkontrolujte, jestli je DATABASE_URL správně nastavený."
echo ""
echo "🎉 Data se nyní ukládají do databáze a přežijí každý redeploy!"




